{
 "title": "Alerts Status",
 "tags": [ "DBmon" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host0",
    "label": "Host0",
    "query": "label_values(up{instance=~'$host'}, instance0)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values({__name__=~\"up\", job=\"linux\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Critical",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",level=\"critical\",instance=~\"$host\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "count(sum(ALERTS{alertstate=\"firing\",level=\"critical\",instance=~\"$host\"}) by (alertname, instance, level))",
     "legendFormat": "Firing"
    },
    {
     "calculatedInterval": "2m",
     "expr": "count(sum(ALERTS{alertstate=\"pending\",level=\"critical\",instance=~\"$host\"}) by (alertname, instance, level))",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Warings",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",level=\"warning\",instance=~\"$host\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "count(sum(ALERTS{alertstate=\"firing\",level=\"warning\"}) by (alertname, instance, level))",
     "legendFormat": "Firing"
    },
    {
     "calculatedInterval": "2m",
     "expr": "count(sum(ALERTS{alertstate=\"pending\",level=\"warning\"}) by (alertname, instance, level))",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Current critical list",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", level=\"critical\",instance=~\"$host\"} == 1"
    }
   ]
  },
  {
   "title": "Current warning list",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", level=\"warning\",instance=~\"$host\"} == 1"
    }
   ]
  },
  {
   "title": "Alert Sent History",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \n  id,\n  name,\n  instance,\n  level,\n  subject,\n  status,\n  description,\n  created_at\nFROM hook\nORDER BY id DESC\nLIMIT 100;"
    }
   ]
  }
 ]
}