{
 "title": "CPU Utilization Details (Cores)",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host0",
    "label": "Host0",
    "query": "label_values(up{instance=~'$host'}, instance0)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_cpu|node_cpu_average\", job!=\"prometheus\"}, instance)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu{instance=\"$host0\"}, cpu)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$host - Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[5m]),1)) ))*100 or (max_over_time(node_cpu_average{instance=~\"$host0\", mode!=\"total\", mode!=\"idle\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$host0\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () ((sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )*100) or (max_over_time(node_cpu_average{instance=~\"$host0\", mode!=\"total\", mode!=\"idle\", mode!=\"wait\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$host0\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m]))),100)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$host - Current CPU Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg by () ((sum by (cpu) ( (clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1))*100 )) or max_over_time(node_cpu_average{instance=~\"$host0\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"iowait\"}[5m])*100,100)) )) or sum by (cpu) (max_over_time(node_cpu_average{instance=~\"$host0\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": " {{cpu}}"
    }
   ]
  },
  {
   "title": "Overall CPU Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "All Cores - total",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () ((avg by (mode) ( \n(clamp_max(rate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100 or \nsum by () (\navg_over_time(node_cpu_average{instance=\"$host0\",mode!=\"total\",mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{instance=\"$host0\",mode!=\"total\",mode!=\"idle\"}[5m])) unless\n(avg_over_time(node_cpu_average{instance=\"$host0\",mode=\"total\",job=\"rds-basic\"}[$interval]) or \navg_over_time(node_cpu_average{instance=\"$host0\",mode=\"total\",job=\"rds-basic\"}[5m]))\n),100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - iowait",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - other",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{instance=\"$host0\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{instance=\"$host0\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100) "
    }
   ]
  },
  {
   "title": "CPU Cores Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Core CPU Usage",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
     "content": "Per CPU usage Information shows  usage for each CPU (Virtual) core.  The Current (most recent) numbers are shown together with history as sparkline"
    }
   ]
  },
  { "title": "$cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "cpu" },
  {
   "title": "$cpu - total",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(\nsum by (cpu) (\n(avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100) or \nsum by () (\navg_over_time(node_cpu_average{instance=\"$host0\",mode!=\"total\",mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{instance=\"$host0\",mode!=\"total\",mode!=\"idle\"}[5m])) unless\n(avg_over_time(node_cpu_average{instance=\"$host0\",mode=\"total\",job=\"rds-basic\"}[$interval]) or \navg_over_time(node_cpu_average{instance=\"$host0\",mode=\"total\",job=\"rds-basic\"}[5m]))\n,100)"
    }
   ]
  },
  {
   "title": "$cpu - user",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - system",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - iowait",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - steal",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - other",
   "type": "pmm-singlestat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host0\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{instance=\"$host0\", cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{instance=\"$host0\",cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100)"
    }
   ]
  }
 ]
}