{
 "title": "Cross Server Graphs - 1m",
 "tags": [ "DBmon" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,1h,24h" },
   { "name": "read_only", "label": "Read-only", "query": "2,0,1" },
   {
    "name": "host0",
    "label": "Host0",
    "query": "label_values(up{instance=~'$host'}, instance0)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values({__name__=~\"up\"}, instance)"
   },
   { "name": "type", "label": "Type", "query": "avg,min,max" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Current cpu usage percentage.",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_cpu_usage:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Wait : I/O",
   "type": "graph",
   "description": "Cpu Waits for I/O. Check disk or network status if this value is high. It could be from random I/O disk read pattern if your disk is not SSD.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_cpu_wait_usage:$type:1m', mode='iowait'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Waits : USER",
   "type": "graph",
   "description": "Cpu Waits for \"USER\". Application use cpu resource too much. This is mostly caused by inefficient query execution.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_cpu_wait_usage:$type:1m', mode='user'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_load_avg:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_mem_usage:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Swap Memory (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_mem_swap_byte:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cached Memory(%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_mem_cached_pct:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Disk Total IO Time",
   "type": "graph",
   "description": "Similar disk Utilization, but sum io times for each device's.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__=~'rec:node_disk_io_ms:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Read Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__=~'rec:node_disk_reads:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Write Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__=~'rec:node_disk_writes:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__=~'rec:node_disk_read_bytes:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__=~'rec:node_disk_write_bytes:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__=~'rec:node_disk_read_latency:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__=~'rec:node_disk_write_latency:$type:1m'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "MySQL overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Connection Usage (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_conn_usage:$type:1m'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_conn_usage:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_conn_runnings:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_conn_runnings:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_slow_queries:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_slow_queries:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Queries/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_questions:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_questions:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DML/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_dmls:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_dmls:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rows/query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_stmt_scans:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_stmt_scans:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "InnoDB status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "InnoDB Check Point Age (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_ckpg_usage:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_ckpg_usage:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB rows read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_row_reads:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_row_reads:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB rows write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_row_writes:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_row_writes:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_trxs:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_trxs:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Transaction History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_trx_hist:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_trx_hist:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer pool reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 88 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_read_reqs:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_read_reqs:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "(max_over_time({__name__='rec:mysql_innodb_disk_reads:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_disk_reads:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "Disk reads - {{ instance }} "
    }
   ]
  },
  {
   "title": "InnoDB Lock Wait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_lock_waits:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_lock_waits:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer pool writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 96 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_write_reqs:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_write_reqs:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Deallocks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_innodb_dead_locks:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_innodb_dead_locks:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "MySQL Replication Delay (sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_repl_delay:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_repl_delay:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "MySQL receive  (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_net_rx_byte:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_net_rx_byte:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL transmit (Bytes)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "(max_over_time({__name__='rec:mysql_net_tx_byte:$type:1m', instance=~'$host'}[$interval]) and on (instance) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))\nor\n(max_over_time({__name__='rec:mysql_net_tx_byte:$type:1m', instance0=~'$host'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network receive (Bytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_net_rx_byte:$type:1m', device!='lo'}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}:{{ device }}"
    }
   ]
  },
  {
   "title": "Network transmit (Bytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "1m",
     "expr": "max_over_time({__name__='rec:node_net_tx_byte:$type:1m', device!=\"lo\"}[$interval]) and on (instance0) (max_over_time({__name__=~'rec:agent_mysql:snap:1m|rec:agent_linux:snap:1m', instance=~'$host'}[$interval]) <= $read_only^2-3 or max_over_time({__name__='rec:mysql_readonly:snap:1m', instance=~'$host'}[$interval]) == $read_only)",
     "legendFormat": "{{ instance }}:{{ device }}"
    }
   ]
  }
 ]
}