{
 "title": "Home Dashboard",
 "tags": [ "DBmon" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,30s,1m,5m,10m,1h,24h" },
   { "name": "read_only", "label": "Read-only", "query": "2,0,1" },
   {
    "name": "host0",
    "label": "Host0",
    "query": "label_values(up{instance=~'$host'}, instance0)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values({__name__=\"up\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Critical",
   "type": "pmm-singlestat-panel",
   "description": "Current critical alerts, which is firing.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",level=\"critical\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Waring",
   "type": "pmm-singlestat-panel",
   "description": "Current waring alerts, which is firing.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",level=\"warning\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Current cpu usage percentage.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "percent(%)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg_over_time({__name__=\"raw:node_cpu_usage\"}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Total IO Time",
   "type": "graph",
   "description": "Similar disk Utilization, but sum io times for each device's.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg_over_time({__name__=\"raw:node_disk_io_ms\"}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network (Bytes)",
   "type": "graph",
   "description": "Network traffic usage. Minus value is transmit bytes, plus value is received bytes.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg_over_time({__name__=\"raw:node_net_rx_byte\", device!=\"lo\"}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only)",
     "legendFormat": "{{ instance }}:{{ device }}_rx"
    },
    {
     "expr": "-1 * (avg_over_time({__name__=\"node_net_tx_byte\", device!=\"lo\"}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))",
     "legendFormat": "{{ instance }}:{{ device }}_tx"
    }
   ]
  },
  { "title": "MySQL Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "MySQL Connection Usage",
   "type": "graph",
   "description": "Current thread usage.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent", "label": "percent(%)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(avg_over_time({__name__=\"raw:mysql_conn_usage\", instance=~'$host'}[$interval]) and on (instance) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))\nor\n(avg_over_time({__name__=\"raw:mysql_conn_usage\", instance0=~'$host'}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Running Threads",
   "type": "graph",
   "description": "Current running threads which is not sleeping.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "threads" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(max_over_time({__name__=\"raw:mysql_conn_runnings\", instance=~'$host'}[$interval]) and on (instance) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))\nor\n(max_over_time({__name__=\"raw:mysql_conn_runnings\", instance0=~'$host'}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "MySQL Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "MySQL Questions",
   "type": "graph",
   "description": "The number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "queries/sec" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(avg_over_time({__name__=\"raw:mysql_questions\", instance=~'$host'}[$interval]) and on (instance) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))\nor\n(avg_over_time({__name__=\"raw:mysql_questions\", instance0=~'$host'}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))",
     "legendFormat": "{{ instance }} (queries/s)"
    }
   ]
  },
  {
   "title": "MySQL Row Average",
   "type": "graph",
   "description": "Rows scan amount per statement. Check used queris if this value is high. Mostly, it's from full scan.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Rows/query" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(max_over_time({__name__=\"raw:mysql_stmt_scans\", instance=~'$host'}[$interval]) and on (instance) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))\nor\n(max_over_time({__name__=\"raw:mysql_stmt_scans\", instance0=~'$host'}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "InnoDB Check Point Age",
   "type": "graph",
   "description": "The maximum checkpoint age is determined by the total length of all transaction log files (`innodb_log_file_size`).\n\nWhen the checkpoint age reaches the maximum checkpoint age, blocks are flushed syncronously. The rules of the thumb is to keep one hour of traffic in those logs and let the checkpointing perform its work as smooth as possible. If you don't do this, InnoDB will do synchronous flushing at the worst possible time, ie when you are busiest.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent", "label": "percent(%)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(avg_over_time({__name__=\"raw:mysql_innodb_ckpg_usage\", instance=~'$host'}[$interval]) and on (instance) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))\nor\n(avg_over_time({__name__=\"raw:mysql_innodb_ckpg_usage\", instance0=~'$host'}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "MySQL Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "MySQL Replication Delay",
   "type": "graph",
   "description": "Shows the number of seconds the Slave host is delayed in replication applying events compared to when the Master host applied them, denoted by the **Seconds_Behind_Master** value, and only applies to a Slave host. The most common reasons for Slaves to lag their Master are:\n\n* Network round trip time - High latency links will lead to non-zero replication lag values\n\n* Single threaded nature of replication channels - Master servers have the advantage of applying changes in parallel, whereas Slaves are only able to apply changes in serial, thus limiting their throughput.  In some cases Group Commit can help but is not always applicable.\n\n* High number of changed rows or computationally expensive SQL - Depending on the replication format (ROW vs STATEMENT), significant changes to the database through high volume of rows modified, or expensive CPU will all contribute to Slaves lagging behind their Master\n\nGenerally adding more CPU or Disk resources can alleviate replication lag issues, up to a point.\n\nIdeally a value of 0 is desired, but be aware that **Seconds_Behind_Master** is an integer value and thus rounding is a factor. If you desire greater precision, consider the Percona Toolkit tool pt-heartbeat, as this graph will automatically take into account this tool and then show you greater resolution.\n\nSee also:",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(max_over_time({__name__=\"raw:mysql_repl_delay\", instance=~\"$host\"}[$interval]) and on (instance) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))\nor\n(max_over_time({__name__=\"raw:mysql_repl_delay\", instance0=~'$host'}[$interval]) and on (instance0) ({__name__=~'raw:agent_mysql|raw:agent_linux', instance=~'$host'} <= $read_only^2-3 or raw:mysql_readonly{instance=~'$host'} == $read_only))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL Replication Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "select\n  concat(instance_name, if(mysql_readonly=1,'(RO)',if(mysql_readonly=0,'(RW)',''))) as instance_name,\n  repl_master,\n  case\n    when mysql_repl_io_stus = 0 then 'ERROR'\n    when mysql_repl_io_stus = 1 then 'OK'\n    else ''\n  end as mysql_repl_io_stus,\n  case\n    when mysql_repl_sql_stus = 0 then 'ERROR'\n    when mysql_repl_sql_stus = 1 then 'OK'\n    else ''\n  end as mysql_repl_sql_stus,\n  if(mysql_repl_delay >= 0, mysql_repl_delay, 'ERROR') as mysql_repl_delay\nfrom(\n  select straight_join\n    alert_instance.id as instance_id,\n    alert_instance.name as instance_name,\n    ifnull(m05.num_value, -1) as mysql_readonly,\n    ifnull(m06.str_value, '') as repl_master,\n    ifnull(m06.num_value, -1) as mysql_repl_io_stus,\n    ifnull(m07.num_value, -1) as mysql_repl_sql_stus,\n    ifnull(m08.num_value, -1) as mysql_repl_delay\n  from alert_instance\n  inner join snapshot_metric m05 on m05.instance = alert_instance.name and m05.name = 'mysql_readonly'\n  inner join snapshot_metric m06 on m06.instance = alert_instance.name and m06.name = 'mysql_repl_io_stus'\n  inner join snapshot_metric m07 on m07.instance = alert_instance.name and m07.name = 'mysql_repl_sql_stus'\n  left join snapshot_metric m08 on m08.instance = alert_instance.name and m08.name = 'mysql_repl_delay'\n) t;"
    }
   ]
  }
 ]
}