{
 "title": "Trends Dashboard",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host0",
    "label": "Host0",
    "query": "label_values(up{instance=~'$host'}, instance0)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Compares the percentage of CPU usage for the current selected range versus the previous day and the previous week for the same time range. This graph is useful to demonstrate how the CPU usage has changed over time by visually overlaying time periods.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((sum by (mode) (\n(clamp_max(rate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[$interval]),1)) or \n(clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[5m]),1)) ))*100 \nor (sum by (mode) (\nclamp_max(((max_over_time(node_cpu_average{instance=\"$host0\", mode!=\"idle\"}[$interval]) or \nmax_over_time(node_cpu_average{instance=\"$host0\", mode!=\"idle\"}[5m]))),100))))",
     "legendFormat": "Busy State"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((sum by (mode) (\n(clamp_max(rate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[$interval] offset 1d),1)) or \n(clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[5m] offset 1d),1)) ))*100 \nor (sum by (mode) (\nclamp_max(((max_over_time(node_cpu_average{instance=\"$host0\", mode!=\"idle\"}[$interval] offset 1d) or \nmax_over_time(node_cpu_average{instance=\"$host0\", mode!=\"idle\"}[5m] offset 1d))),100))))",
     "legendFormat": "Busy State 1d ago"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg by (instance) ((sum by (mode) (\n(clamp_max(rate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[$interval] offset 1w),1)) or \n(clamp_max(irate(node_cpu{instance=\"$host0\",mode!=\"idle\"}[5m] offset 1w),1)) ))*100 \nor (sum by (mode) (\nclamp_max(((max_over_time(node_cpu_average{instance=\"$host0\", mode!=\"idle\"}[$interval] offset 1w) or \nmax_over_time(node_cpu_average{instance=\"$host0\", mode!=\"idle\"}[5m] offset 1w))),100))))",
     "legendFormat": "Busy State 1w ago"
    }
   ]
  },
  {
   "title": "I/O Read Activity",
   "type": "graph",
   "description": "Shows the comparison of I/O Read Activity in terms of bytes read for the current selected range versus the previous day and the previous week for the same time range. This graph is useful to demonstrate how I/O Read Activity has changed over time by visually overlaying time periods. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=\"$host0\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host0\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=\"$host0\"}[$interval] offset 1d) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host0\"}[5m] offset 1d) * 1024",
     "legendFormat": "Page In 1d ago"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=\"$host0\"}[$interval] offset 1w) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host0\"}[5m] offset 1w) * 1024",
     "legendFormat": "Page In 1w ago"
    }
   ]
  },
  {
   "title": "I/O Write Activity",
   "type": "graph",
   "description": "Shows the comparison of I/O Write Activity in terms of bytes written for the current selected range versus the previous day and the previous week for the same time range. This graph is useful to demonstrate how I/O Write Activity has changed over time by visually overlaying time periods.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=\"$host0\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host0\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=\"$host0\"}[$interval] offset 1d) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host0\"}[5m] offset 1d) * 1024",
     "legendFormat": "Page Out 1d ago"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=\"$host0\"}[$interval] offset 1w) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host0\"}[5m] offset 1w) * 1024",
     "legendFormat": "Page Out 1w ago"
    }
   ]
  },
  { "title": "MySQL Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "MySQL Questions",
   "type": "graph",
   "description": "Shows the comparison of the MySQL Questions for the current selected range versus the previous day and the previous week for the same time range. This graph is useful to demonstrate how MySQL Questions has changed over time by visually overlaying time periods.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_questions{instance=\"$host\"}[5m])",
     "legendFormat": "Questions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval] offset 1d) or irate(mysql_global_status_questions{instance=\"$host\"}[5m] offset 1d)",
     "legendFormat": "Questions 1d ago"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval] offset 1w) or irate(mysql_global_status_questions{instance=\"$host\"}[5m] offset 1w)",
     "legendFormat": "Questions 1w ago"
    }
   ]
  },
  {
   "title": "InnoDB Rows Read",
   "type": "graph",
   "description": "Shows the comparison of the InnoDB Rows Read for the current selected range versus the previous day and the previous week for the same time range. This graph is useful to demonstrate how InnoDB Rows Read has changed over time by visually overlaying time periods.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation=\"read\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation=\"read\"}[5m])",
     "legendFormat": "Rows {{ operation }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation=\"read\"}[$interval] offset 1d) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation=\"read\"}[5m] offset 1d)",
     "legendFormat": "Rows {{ operation }} 1d ago"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation=\"read\"}[$interval] offset 1w) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation=\"read\"}[5m] offset 1w)",
     "legendFormat": "Rows {{ operation }} 1w ago"
    }
   ]
  },
  {
   "title": "InnoDB Rows Changed",
   "type": "graph",
   "description": "Shows the comparison of innoDB Rows Changed for the current selected range versus the previous day and the previous week for the same time range. This graph is useful to demonstrate how the InnoDB Rows Changed has fluctuated over time by visually overlaying time periods.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation!=\"read\"}[$interval])) or sum(irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation!=\"read\"}[5m]))",
     "legendFormat": "Rows inserted+updated+deleted"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation!=\"read\"}[$interval] offset 1d)) or sum(irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation!=\"read\"}[5m] offset 1d))",
     "legendFormat": "Rows inserted+updated+deleted 1d ago"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation!=\"read\"}[$interval] offset 1w)) or sum(irate(mysql_global_status_innodb_row_ops_total{instance=\"$host\", operation!=\"read\"}[5m] offset 1w))",
     "legendFormat": "Rows inserted+updated+deleted 1w ago"
    }
   ]
  }
 ]
}